### ISSUE TITLE
Questions regarding `$PAGER`

### ISSUE THREAD

**Issue by xfzv** [hankertrix/augment-command.yazi#1]
First of all, thanks for this awesome plug-in!

When using `i` to use the pager:

```toml

[[manager.prepend_keymap]]
on = ["i"]
run = "plugin augment-command --args='pager'"
desc = "Open files with the default pager"
```

(my `$PAGER` variable):

```console
% echo $PAGER
less -RF
```

Due to (I guess) `-F, --quit-if-one-screen`

> man less

```
  -F or --quit-if-one-screen
              Causes less to automatically exit if the entire file can be displayed on the first screen.
```

with files that contain only a few lines, after hovering the desired file and pressing `i`, `yazi` remains focused and I have to exit `yazi` to see the file content in the terminal. This doesn't occur with files with content that cannot fit on the first screen since in this case `-F` isn't "triggered".

Is there a workaround for this?

Another question: how could I use [`bat`](https://github.com/sharkdp/bat) as PAGER? Ideally I'd like to pass arguments like `-p, --plain`.

**Comment by hankertrix** [comment]
I just fixed the pager command so that the -F flag gets removed if found in the `$PAGER` environment variable.

You can now use the augmented shell command to use [`bat`](https://github.com/sharkdp/bat) as a pager. The documentation can be found in the README.md file.

**Comment by hankertrix** [comment]
You're welcome!

The plugin now patches the less command given to properly remove the F flag, even removing it from the LESS environment variable.

**Comment by hankertrix** [comment]
Awesome, thanks!

I think you should be able to simplify your command to use `bat` as a pager to this:
```toml
run = '''plugin augment-command --args="shell 'bat -p --pager \"less\" \"$@\"' --block --confirm"'''
```

**Comment by hankertrix** [comment]
Yeap that is correct!

**Comment by hankertrix** [comment]
Hmmm I don't think I can do anything about this behaviour, since `bat` automatically passes a few flags to `less` if no command line options are specified, including the `-F` flag.

`man bat`:

```
       --pager <command>

              Determine which pager is used. This option will override the PAGER and BAT_PAGER environment variables. The default pager is 'less'. To control when the pager  is  used,  see  the
              '--paging' option. Example: '--pager "less -RF"'.

              Note:  By default, if the pager is set to 'less' (and no command-line options are specified), 'bat' will pass the following command line options to the pager: '-R'/'--RAW-CONTROL-
              CHARS', '-F'/'--quit-if-one-screen' and '-X'/'--no-init'. The last option ('-X') is only used for 'less' versions older than 530. The '-R' option is needed to interpret ANSI  col‐
              ors correctly. The second option ('-F') instructs less to exit immediately if the output size is smaller than the vertical size of the terminal. This is convenient for small files
              because  you do not have to press 'q' to quit the pager. The third option ('-X') is needed to fix a bug with the '--quit-if-one-screen' feature in old versions of 'less'. Unfortu‐
              nately, it also breaks mouse-wheel support in 'less'. If you want to enable mouse-wheel scrolling on older versions of 'less', you can pass just '-R' (as  in  the  example  above,
              this will disable the quit-if-one-screen feature). For less 530 or newer, it should work out of the box.
```

Passing just one flag to `less` should stop this default behaviour. Alternatively, if you don't want to pass any flags to `less`, you can also pass `--` to `less` to stop this default behaviour, like this:

```
run = '''plugin augment-command --args="shell 'bat -p --pager \"less --\" \"$@\"' --block --confirm"'''
```

I think the above command should work on both your Arch Linux and Gentoo install.

**Comment by hankertrix** [comment]
You're welcome!

**Comment by hankertrix** [comment]
> Hmmm I don't think I can do anything about this behaviour

It turns out I can actually do something about it and commit e992daccfba5dc92129e3d044383aa0974acf4e4 fixes the bat command when the less command is passed without any arguments.

**Comment by hankertrix** [comment]
Excellent!

**Comment by hankertrix** [comment]
You can use the triple quotes option, like this:

```toml
[[manager.prepend_keymap]]
on = ["i"]
run = '''plugin augment-command -- shell --block 'bat -p --pager "less" $@''''
desc = "Open with bat"
```

**Comment by hankertrix** [comment]
I see, sure thing. For more complicated commands, I think it is still necessary to escape or use the triple quotes option, but the recent Yazi change using `--` has made it much cleaner to use shell commands.

You're welcome!

**Comment by hankertrix** [comment]
With reference to [this comment](https://github.com/hankertrix/augment-command.yazi/commit/4ba159d6e065637cf6dad28f128a16a48bf3e475#commitcomment-152588584) from the Yazi developer, you should use this instead:

```toml
[[manager.prepend_keymap]]
on = "i"
run = "plugin augment-command -- shell --block 'bat -p --pager less $@'"
desc = "Open with bat"
```
