### ISSUE TITLE
Crashes yazi due to `attempt to call a nil value (global 'Command')`

### ISSUE THREAD

**Issue by redbeardymcgee** [hankertrix/augment-command.yazi#2]
```
❯ yazi --version
Yazi 0.3.0 (Nixpkgs 2024-08-01)
```
```
❯ yazi
Error: Lua runtime failed

Caused by:
    runtime error: [string "augment-command"]:269: attempt to call a nil value (global 'Command')
    stack traceback:
        [C]: in global 'Command'
        [string "augment-command"]:269: in upvalue 'shell_command_exists'
        [string "augment-command"]:288: in upvalue 'initialise_plugin'
        [string "augment-command"]:1080: in function 'augment-command.setup'
        [C]: in method 'setup'
        [string "init.lua"]:16: in main chunk
    stack traceback:
        [C]: in method 'setup'
        [string "init.lua"]:16: in main chunk
```

In the `yazi` discord this comes up periodically and the answer every time has been "Command only exists in the async context." I don't fully comprehend what that means yet, but maybe it's a useful clue for you.

I've tried this on every commit since commit 7209ca418a267bfa0f1b41a5311ad2618130b889 and the error is always the same.

**Comment by hankertrix** [comment]
> In the `yazi` discord this comes up periodically and the answer every time has been "Command only exists in the async context."

Thanks for this, it helped me figure out the problem immediately. The issue is due to the plugin calling `Command` in the plugin setup function, which is in a synchronous context instead of an asynchronous context, so `Command` isn't available then.
