### ISSUE TITLE
`skip_single_subdirectory_on_enter` does not work on macOS

### ISSUE THREAD

**Issue by tilliwilli** [hankertrix/augment-command.yazi#3]
Since macOS, being a Unix and based on BSD, does not ship GNU `ls` out of the box, but a very crippled BSD `ls`, the `skip_single_subdirectory_on_enter` and `skip_single_subdirectory_on_leave` functionalities do not work out of the box.

The BSD `ls` does not support `--group-directories-first` at all, and it needs the directory as the last argument.

Any sane macOS user that opened the terminal at least once has already realized that and installed the GNU coreutils asap, which makes the "correct" `ls` reachable as `gls` when installed via Homebrew. This is usually aliased to `ls` in a `.zshrc` or somewhere, but these aliases or functions do not apply to Yazi's `Command` command.

So, the easiest fix for me locally was to change the source code of the plugin to invoke `gls` directly, but this is obviosly no general solution.

I guess the cleanest solution is to check for macOS in the code and call `gls` appropriately? And then make macOS users require to install GNU coreutils.

**Comment by hankertrix** [comment]
Reopening the issue as I want to reimplement this functionality using `find` instead of `ls` to avoid such incompatibility issues with the output of the `ls` command. Seems like the output of `ls` shouldn’t be parsed as it is not consistent across all implementations of the command.

**Comment by hankertrix** [comment]
@tilliwilli the plugin has been updated to use the `find` command, would appreciate it if you could test it to see if it works.

**Comment by tilliwilli** [comment]
Just tested it with the latest changes, works flawlessly 👍 (on my Mac anyway, with lots of stuff installed, but I don't think there is a special version of `find` installed)

```
❯ type find
find is an alias for noglob find
find is /usr/bin/find
```

**Comment by hankertrix** [comment]
Awesome! Thank you for testing!
