### ISSUE TITLE
Deprecated API about args

### ISSUE THREAD

**Issue by c02y** [hankertrix/augment-command.yazi#6]
![image](https://github.com/user-attachments/assets/e2dc21ab-75d2-4c33-8517-4df72a3c1062)

FYI:
- yazi v0.4
- https://github.com/sxyazi/yazi/pull/1966

**Comment by hankertrix** [comment]
Oh wow, Yazi v0.4 has been released. That's quick.

I will need some time to update the plugin as I have quite a few changes I would like to make with the v0.4 release, one of the big ones is splitting the code into separate files by making use of the assets directory.

The ability to pass arguments to the plugin is also something I will have to think about as I might not need to parse the arguments in the plugin anymore, but that will be breaking the plugin's API as well. I will need to look more into this `job` argument being passed, but from what I've seen it will likely simplify the plugin's API and make it more performant as I don't have to parse arguments in the plugin any more.

The next commit will likely be a massive breaking change release, so I will keep a v0.3.3 branch around, but it will not be updated.

**Comment by hankertrix** [comment]
I have decided not to do the breaking change release, as splitting up the plugin's code does not work. For more details you can refer to the commit message in commit https://github.com/hankertrix/augment-command.yazi/commit/b1984a6f4a0962717631980cfc3011363b8e3652.

The plugin in its current state is backwards compatible with `v0.3.x`, so there is no need for a `v0.3.x` tag.
