### ISSUE TITLE
parent_arrow does not work

### ISSUE THREAD

**Issue by chungyinleo** [hankertrix/augment-command.yazi#7]
Thank you for the great plugin!

The new command `parent_arrow` no longer work after the latest commit. No error messages displayed, it just does nothing.
Switching back to the previous commit still works, the only problem is there would be a "Deprecated API" warning message.

**Comment by hankertrix** [comment]
Hmmm it looks like Yazi isn't converting numbers to the number type in Lua.

Seems like I still have to parse the arguments.
